# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-01 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'InActive'), (2, 'Trash')], default=0, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigngroup', to='management.Group', verbose_name='Group')),
                ('student', models.ManyToManyField(related_name='assign_student', to='management.Student', verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='AssignGroupDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_student_status', models.IntegerField(choices=[(0, 'Active'), (1, 'InActive'), (2, 'Trash')], default=0, verbose_name='Assign Student Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('assign_group_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_group_detail', to='management.AssignGroup', verbose_name='Assign Group')),
                ('assign_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_student_detail', to='management.Student', verbose_name='Student')),
            ],
        ),
    ]
