# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-01 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_assigngroup_assigngroupdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigngroup',
            name='student',
        ),
    ]
