# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_assigngroup_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'InActive'), (2, 'Trash')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='assigngroupdetail',
            name='assign_group_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_group_detail', to='management.Group', verbose_name='Assign Group'),
        ),
    ]
