# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20190502_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigngroupdetail',
            name='assign_student_status',
            field=models.IntegerField(choices=[(0, 'DisConnect'), (1, 'Connect'), (2, 'Block')], default=0, verbose_name='Assign Student Status'),
        ),
    ]
