# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-05 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0007_auto_20190502_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignGroupComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('assign_group_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigngroupcomments', to='management.Group', verbose_name='Assign Group Comments')),
                ('assign_group_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_group_comments', to='management.Group', verbose_name='Assign Group Comments')),
                ('group_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigngroupcomments_Created_By', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
