# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_group_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigngroupdetail',
            name='read_status',
            field=models.IntegerField(choices=[(0, 'Unread'), (1, 'Read')], default=0, verbose_name='Read Status'),
        ),
    ]
